export interface Rug {
  id: string
  title: string
  slug: string
  collection: string
  style: "modern" | "traditional" | "abstract" | "transitional"
  weaveType: "handwoven" | "hand-knotted" | "flatweave" | "kilim"
  material: string
  dimensions: string
  price: number
  primaryColor: string
  images: string[]
  description: string
  isFeatured: boolean
  origin?: string
}

export const COLLECTIONS = [
  "Moroccan Dreams",
  "Persian Heritage",
  "Modern Minimalist",
  "Boho Fusion",
  "Vintage Elegance",
  "Turkish Kilims",
]

export const rugsData: Rug[] = [
  {
    id: "1",
    title: "Marrakech Midnight",
    slug: "marrakech-midnight",
    collection: "Moroccan Dreams",
    style: "traditional",
    weaveType: "hand-knotted",
    material: "100% wool",
    dimensions: "8' x 10'",
    price: 2400,
    primaryColor: "Navy",
    images: ["/moroccan-navy-rug.jpg", "/moroccan-rug-detail.jpg", "/traditional-rug.jpg"],
    description: "Hand-knotted Moroccan rug with intricate geometric patterns and rich navy tones.",
    isFeatured: true,
    origin: "Morocco",
  },
  {
    id: "2",
    title: "Sahara Sand",
    slug: "sahara-sand",
    collection: "Moroccan Dreams",
    style: "traditional",
    weaveType: "hand-knotted",
    material: "100% wool",
    dimensions: "6' x 9'",
    price: 1800,
    primaryColor: "Cream",
    images: ["/moroccan-cream-rug.jpg", "/sahara-texture.jpg"],
    description: "Warm cream and terracotta tones create a welcoming Moroccan aesthetic.",
    isFeatured: true,
    origin: "Morocco",
  },
  {
    id: "3",
    title: "Casablanca Harmony",
    slug: "casablanca-harmony",
    collection: "Moroccan Dreams",
    style: "abstract",
    weaveType: "handwoven",
    material: "100% wool",
    dimensions: "5' x 7'",
    price: 1200,
    primaryColor: "Terracotta",
    images: ["/moroccan-terracotta-rug.jpg"],
    description: "Modern Moroccan design with traditional weaving techniques.",
    isFeatured: false,
    origin: "Morocco",
  },
  {
    id: "4",
    title: "Persian Garden",
    slug: "persian-garden",
    collection: "Persian Heritage",
    style: "traditional",
    weaveType: "hand-knotted",
    material: "100% wool with silk accents",
    dimensions: "9' x 12'",
    price: 4500,
    primaryColor: "Wine",
    images: ["/persian-garden-rug.jpg", "/persian-floral.jpg"],
    description: "Exquisite Persian carpet featuring traditional floral motifs and rich jewel tones.",
    isFeatured: true,
    origin: "Iran",
  },
  {
    id: "5",
    title: "Tabriz Majesty",
    slug: "tabriz-majesty",
    collection: "Persian Heritage",
    style: "traditional",
    weaveType: "hand-knotted",
    material: "100% silk",
    dimensions: "8' x 10'",
    price: 5200,
    primaryColor: "Cream",
    images: ["/tabriz-cream-rug.jpg"],
    description: "Silk Persian rug with intricate medallion design and exceptional craftsmanship.",
    isFeatured: false,
    origin: "Iran",
  },
  {
    id: "6",
    title: "Isfara Gold",
    slug: "isfara-gold",
    collection: "Persian Heritage",
    style: "traditional",
    weaveType: "hand-knotted",
    material: "100% wool",
    dimensions: "7' x 9'",
    price: 2800,
    primaryColor: "Gold",
    images: ["/persian-gold-rug.jpg"],
    description: "Warm gold tones with traditional Persian patterns.",
    isFeatured: false,
    origin: "Iran",
  },
  {
    id: "7",
    title: "Minimalist Canvas",
    slug: "minimalist-canvas",
    collection: "Modern Minimalist",
    style: "modern",
    weaveType: "flatweave",
    material: "100% wool",
    dimensions: "8' x 10'",
    price: 1400,
    primaryColor: "Charcoal",
    images: ["/modern-charcoal-rug.jpg"],
    description: "Contemporary flatweave rug with clean lines and neutral palette.",
    isFeatured: true,
    origin: "Turkey",
  },
  {
    id: "8",
    title: "Urban Neutral",
    slug: "urban-neutral",
    collection: "Modern Minimalist",
    style: "modern",
    weaveType: "flatweave",
    material: "100% wool",
    dimensions: "6' x 9'",
    price: 1100,
    primaryColor: "Oatmeal",
    images: ["/modern-oatmeal-rug.jpg"],
    description: "Versatile modern rug that complements any contemporary space.",
    isFeatured: false,
    origin: "Turkey",
  },
  {
    id: "9",
    title: "Geometric Mono",
    slug: "geometric-mono",
    collection: "Modern Minimalist",
    style: "abstract",
    weaveType: "handwoven",
    material: "100% wool",
    dimensions: "5' x 7'",
    price: 950,
    primaryColor: "Grey",
    images: ["/geometric-grey-rug.jpg"],
    description: "Minimalist geometric design in sophisticated grey tones.",
    isFeatured: false,
    origin: "Turkey",
  },
  {
    id: "10",
    title: "Boho Wanderlust",
    slug: "boho-wanderlust",
    collection: "Boho Fusion",
    style: "abstract",
    weaveType: "handwoven",
    material: "100% jute and wool blend",
    dimensions: "7' x 9'",
    price: 1300,
    primaryColor: "Multi-color",
    images: ["/boho-multicolor-rug.jpg"],
    description: "Eclectic boho design with natural jute and wool textures.",
    isFeatured: true,
    origin: "India",
  },
  {
    id: "11",
    title: "Earthy Harmony",
    slug: "earthy-harmony",
    collection: "Boho Fusion",
    style: "traditional",
    weaveType: "handwoven",
    material: "Wool and cotton",
    dimensions: "6' x 8'",
    price: 1050,
    primaryColor: "Terracotta",
    images: ["/boho-terracotta-rug.jpg"],
    description: "Warm earthy tones blend traditional and bohemian styles.",
    isFeatured: false,
    origin: "India",
  },
  {
    id: "12",
    title: "Sunset Weave",
    slug: "sunset-weave",
    collection: "Boho Fusion",
    style: "abstract",
    weaveType: "handwoven",
    material: "100% wool",
    dimensions: "5' x 8'",
    price: 900,
    primaryColor: "Orange",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Vibrant bohemian rug with sunset-inspired color palette.",
    isFeatured: false,
    origin: "India",
  },
  {
    id: "13",
    title: "Victorian Elegance",
    slug: "victorian-elegance",
    collection: "Vintage Elegance",
    style: "traditional",
    weaveType: "hand-knotted",
    material: "100% wool",
    dimensions: "8' x 10'",
    price: 3200,
    primaryColor: "Burgundy",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Classic vintage design with rich burgundy base and gold accents.",
    isFeatured: true,
    origin: "Turkey",
  },
  {
    id: "14",
    title: "Antique Charm",
    slug: "antique-charm",
    collection: "Vintage Elegance",
    style: "traditional",
    weaveType: "hand-knotted",
    material: "100% wool",
    dimensions: "7' x 9'",
    price: 2600,
    primaryColor: "Cream",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Aged patina effect gives this rug authentic vintage character.",
    isFeatured: false,
    origin: "Turkey",
  },
  {
    id: "15",
    title: "Heritage Stone",
    slug: "heritage-stone",
    collection: "Vintage Elegance",
    style: "transitional",
    weaveType: "hand-knotted",
    material: "100% wool",
    dimensions: "6' x 9'",
    price: 1900,
    primaryColor: "Grey",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Transitional vintage design blending classic and contemporary elements.",
    isFeatured: false,
    origin: "Turkey",
  },
  {
    id: "16",
    title: "Ankara Midnight",
    slug: "ankara-midnight",
    collection: "Turkish Kilims",
    style: "traditional",
    weaveType: "kilim",
    material: "100% wool",
    dimensions: "7' x 10'",
    price: 1600,
    primaryColor: "Navy",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Traditional Turkish kilim with bold geometric patterns.",
    isFeatured: true,
    origin: "Turkey",
  },
  {
    id: "17",
    title: "Anatolia Red",
    slug: "anatolia-red",
    collection: "Turkish Kilims",
    style: "traditional",
    weaveType: "kilim",
    material: "100% wool",
    dimensions: "6' x 8'",
    price: 1300,
    primaryColor: "Red",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Vibrant Turkish kilim with traditional motifs.",
    isFeatured: false,
    origin: "Turkey",
  },
  {
    id: "18",
    title: "Ottoman Gold",
    slug: "ottoman-gold",
    collection: "Turkish Kilims",
    style: "traditional",
    weaveType: "kilim",
    material: "100% wool",
    dimensions: "5' x 7'",
    price: 1000,
    primaryColor: "Gold",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Hand-woven Turkish kilim with golden tones and geometric patterns.",
    isFeatured: false,
    origin: "Turkey",
  },
  {
    id: "19",
    title: "Silk Blend Luxury",
    slug: "silk-blend-luxury",
    collection: "Persian Heritage",
    style: "traditional",
    weaveType: "hand-knotted",
    material: "Wool with silk blend",
    dimensions: "8' x 10'",
    price: 3800,
    primaryColor: "Champagne",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Ultra-luxe blend featuring silk highlights for added shimmer.",
    isFeatured: true,
    origin: "Iran",
  },
  {
    id: "20",
    title: "Neutral Tone Canvas",
    slug: "neutral-tone-canvas",
    collection: "Modern Minimalist",
    style: "modern",
    weaveType: "flatweave",
    material: "100% wool",
    dimensions: "9' x 12'",
    price: 1600,
    primaryColor: "Beige",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Large contemporary rug perfect for spacious modern interiors.",
    isFeatured: true,
    origin: "Turkey",
  },
  {
    id: "21",
    title: "Bohemian Spirit",
    slug: "bohemian-spirit",
    collection: "Boho Fusion",
    style: "abstract",
    weaveType: "handwoven",
    material: "Jute, wool, cotton blend",
    dimensions: "8' x 10'",
    price: 1450,
    primaryColor: "Natural",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Natural fiber bohemian blend with sustainable materials.",
    isFeatured: true,
    origin: "India",
  },
  {
    id: "22",
    title: "Desert Rose",
    slug: "desert-rose",
    collection: "Moroccan Dreams",
    style: "abstract",
    weaveType: "handwoven",
    material: "100% wool",
    dimensions: "7' x 9'",
    price: 1350,
    primaryColor: "Rose",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Soft rose tones with Moroccan-inspired geometric patterns.",
    isFeatured: false,
    origin: "Morocco",
  },
  {
    id: "23",
    title: "Contemporary Lines",
    slug: "contemporary-lines",
    collection: "Modern Minimalist",
    style: "modern",
    weaveType: "flatweave",
    material: "100% wool",
    dimensions: "6' x 8'",
    price: 980,
    primaryColor: "Taupe",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Clean lines and contemporary color palette.",
    isFeatured: false,
    origin: "Turkey",
  },
  {
    id: "24",
    title: "Royal Elegance",
    slug: "royal-elegance",
    collection: "Persian Heritage",
    style: "traditional",
    weaveType: "hand-knotted",
    material: "100% wool",
    dimensions: "9' x 12'",
    price: 3500,
    primaryColor: "Deep Blue",
    images: ["/placeholder.svg?height=600&width=600"],
    description: "Regal Persian carpet with traditional court-inspired design.",
    isFeatured: false,
    origin: "Iran",
  },
]
